"""`kb index` — rebuild `_index.md` and `_backlinks.json` from frontmatter.

Pure bookkeeping: walk the articles, read their frontmatter, write the two derived
files. No model is involved and none is needed — nothing here is a judgment call.

The index is always regenerated and never merged. It is derived data, so any other
copy of it is disposable by definition; refusing to write because the file looks
modified would leave a broken index in place, which is the worse failure.
"""

import json
from collections import defaultdict
from dataclasses import dataclass
from pathlib import Path

from .. import config, schema
from ..errors import VaultNotFoundError, run
from ..output import DryRunOption, JsonOption, console, emit_json, stderr

HEADER = """# Knowledge Index

Master catalog. **This is the entry point** — an agent starts here, finds the articles it
needs, and reads only those.

**Generated by `kb index`. Do not hand-edit — regenerate.**

The rules this vault follows: run `kb schema`.
"""

CONVENTIONS = """## Conventions

- Every article is a markdown file with YAML frontmatter. The frontmatter makes it findable;
  the body is the document.
- **Wikilinks are `[[path/slug\\|Title]]`, never `[[Title]]` alone.** Links resolve by
  *filename*, not by the `title:` field — a bare title link matches nothing and silently
  creates an empty note when clicked. Inside a table the pipe must be escaped (`\\|`) or it is
  parsed as a column separator and the link breaks.
- `status`: `stable` (default) or `active`. An `active` article is current position, not fact.
- `reference/` articles are **stubs pointing at files elsewhere** and carry a `path:` field.
  Follow it to the real document; never answer from the stub. Every other directory holds the
  document itself.
- A document moves into this vault only if its location elsewhere was accidental.
"""


@dataclass(frozen=True)
class IndexResult:
    """What one `kb index` run produced."""

    articles: int
    directories: int
    backlinks: int
    index_path: Path
    backlinks_path: Path
    failures: list[tuple[Path, str]]


def index(as_json: JsonOption = False, dry_run: DryRunOption = False) -> None:
    """Rebuild _index.md and _backlinks.json from every article's frontmatter."""
    with run():
        vault = config.load_config().vault
        if not vault.is_dir():
            raise VaultNotFoundError(f"no vault at {vault}; run `kb init` or set KB_VAULT")
        result = rebuild(vault, write=not dry_run)
        if as_json:
            emit_json(
                {
                    "articles": result.articles,
                    "directories": result.directories,
                    "backlinks": result.backlinks,
                    "index": str(result.index_path),
                    "backlinks_file": str(result.backlinks_path),
                    "dry_run": dry_run,
                    "unreadable": [{"path": str(path), "reason": reason} for path, reason in result.failures],
                }
            )
            return
        for path, reason in result.failures:
            stderr.print(f"[yellow]skipped[/yellow] {path.name}: {reason}")
        verb = "Would index" if dry_run else "Indexed"
        console.print(
            f"{verb} {result.articles} article(s) across {result.directories} director(ies); "
            f"{result.backlinks} article(s) have inbound links."
        )
        if not dry_run:
            console.print(f"[dim]{result.index_path}\n{result.backlinks_path}[/dim]")


def rebuild(vault: Path, write: bool = True) -> IndexResult:
    """Regenerate both derived files. Returns what was produced, written or not."""
    articles, failures = schema.load_vault(vault)
    articles.sort(key=lambda article: article.slug)
    backlinks = build_backlinks(articles)
    index_text = render_index(articles)
    index_path = vault / schema.INDEX_FILE
    backlinks_path = vault / schema.BACKLINKS_FILE
    if write:
        index_path.write_text(index_text, encoding="utf-8")
        backlinks_path.write_text(render_backlinks(articles), encoding="utf-8")
    return IndexResult(
        articles=len(articles),
        directories=len({article.directory for article in articles}),
        backlinks=len(backlinks),
        index_path=index_path,
        backlinks_path=backlinks_path,
        failures=failures,
    )


def build_backlinks(articles: list[schema.Article]) -> dict[str, list[str]]:
    """For each article, which articles link to it.

    Only links that resolve to a real article are recorded. A broken link is a lint
    finding, not a backlink.
    """
    known = {article.slug for article in articles}
    inbound: defaultdict[str, set[str]] = defaultdict(set)
    for article in articles:
        for link in article.links():
            target = link.target.removesuffix(".md")
            if target in known and target != article.slug:
                inbound[target].add(article.slug)
    return {target: sorted(sources) for target, sources in sorted(inbound.items())}


def render_backlinks(articles: list[schema.Article]) -> str:
    """The `_backlinks.json` text, byte for byte as `kb index` writes it.

    Shared with `kb doctor`, which decides whether the file is up to date by comparing
    against this. Two spellings of the same JSON would make doctor report drift that
    does not exist.
    """
    return json.dumps(build_backlinks(articles), indent=2, sort_keys=True) + "\n"


def render_index(articles: list[schema.Article]) -> str:
    """The full `_index.md` text: a header, one table per directory, the conventions."""
    by_directory: defaultdict[str, list[schema.Article]] = defaultdict(list)
    for article in articles:
        by_directory[article.directory].append(article)

    extra = sorted(set(by_directory) - set(schema.DIRECTORIES))
    ordered = [(name, schema.DIRECTORIES[name]) for name in schema.DIRECTORIES]
    ordered += [(name, "not a directory SCHEMA.md defines") for name in extra]

    sections = [HEADER, "---\n"]
    for name, description in ordered:
        found = by_directory.get(name, [])
        if not found and name in extra:
            continue
        sections.append(f"## {name}/ — {description}\n")
        sections.append(_section(found))
    sections.append("---\n")
    sections.append(CONVENTIONS)
    return "\n".join(sections)


def _section(articles: list[schema.Article]) -> str:
    if not articles:
        return "*(empty)*\n"
    rows = ["| Article | Status | Systems | Summary |", "|---|---|---|---|"]
    rows += [_row(article) for article in articles]
    return "\n".join(rows) + "\n"


def _row(article: schema.Article) -> str:
    link = f"[[{article.slug}\\|{_cell(article.title or article.slug)}]]"
    if article.is_active:
        status = "**active**"
    elif article.is_superseded:
        status = "*superseded*"
    else:
        status = _cell(article.status)
    systems = _cell(", ".join(article.list_field("systems")))
    return f"| {link} | {status} | {systems} | {_cell(article.summary)} |"


def _cell(text: str) -> str:
    """Make free text safe inside a table cell. See `schema.table_cell`."""
    return schema.table_cell(text)
